modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/CraftingTweaks/issues"

[[mods]]
modId="craftingtweaks"
version="${mod_version}"
displayName="CraftingTweaks"
displayURL="https://mods.twelveiterations.com/mc/craftingtweaks"
logoFile="craftingtweaks-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Allows you to rotate, balance or clear the crafting matrix by the press of a button, in any (supported) crafting window.
'''

[[dependencies.craftingtweaks]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingtweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingtweaks]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"